src/OrchardCore.Transformalize/Controllers/FileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement;
using TransformalizeModule.Models;
using TransformalizeModule.Services;
using TransformalizeModule.Services.Contracts;

namespace TransformalizeModule.Controllers {

   [Authorize]
   public class FileController : Controller {

      private readonly CombinedLogger<FileController> _logger;
      private readonly ICustomFileStore _formFileStore;
      private readonly IFileService _fileService;
      private readonly IContentManager _contentManager;

      public FileController(
         ICustomFileStore formFileStore,
         IContentManager contentManager,
         IFileService fileService,
         CombinedLogger<FileController> logger
      ) {
         _logger = logger;
         _fileService = fileService;
         _formFileStore = formFileStore;
         _contentManager = contentManager;
      }

      public async Task<ActionResult> Index(string contentItemId) {

         var part = await _fileService.GetFilePart(contentItemId);
         if (part == null) {
            return NotFound();
         }
         var fileInfo = await _formFileStore.GetFileInfoAsync(part.FullPath.Text);

         return new FileStreamResult(await _formFileStore.GetFileStreamAsync(fileInfo), part.MimeType());
      }


      [HttpPost]
      [RequestSizeLimit(209_715_200)]
      public async Task<ContentResult> Upload() {

         if (!User.Identity.IsAuthenticated) {
            return GetResult(string.Empty, "Unauthorized");
         }

         // todo extract this to service
         if (Request.HasFormContentType && Request.Form.Files != null && Request.Form.Files.Count > 0) {
            var file = Request.Form.Files[0];
            if (file != null && file.Length > 0) {

               var contentItem = await _contentManager.NewAsync("TransformalizeFile");
               var part = contentItem.As<TransformalizeFilePart>();
               part.OriginalName.Text = file.FileName;

               var filePath = Path.Combine(Common.GetSafeFilePath(part, HttpContext.User.Identity.Name));

               using (var stream = file.OpenReadStream()) {
                  await _formFileStore.CreateFileFromStreamAsync(filePath, stream, true);
               }

               var fileInfo = await _formFileStore.GetFileInfoAsync(filePath);

               part.FullPath.Text = fileInfo.Path;

               contentItem.Apply(part);

               await _contentManager.CreateAsync(contentItem);

               return GetResult(contentItem.ContentItemId, file.FileName);
            }
         }

         return GetResult(string.Empty, "Error");
      }

      private static ContentResult GetResult(string id, string message) {
         var data = string.Format("{{ \"id\":\"{0}\", \"message\":\"{1}\" }}", id, message);
         return new ContentResult {
            Content = data,
            ContentType = "text/json"
         };
      }
      
   }
}

src/OrchardCore.Transformalize/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using OrchardCore.ContentManagement;
using OrchardCore.Modules.Services;
using OrchardCore.Title.Models;
using TransformalizeModule.Models;
using TransformalizeModule.Services;
using TransformalizeModule.Services.Contracts;
using TransformalizeModule.ViewModels;

namespace TransformalizeModule.Controllers {

   [Authorize]
   public class ReportController : Controller {

      private readonly IReportService _reportService;
      private readonly ISlugService _slugService;
      private readonly CombinedLogger<ReportController> _logger;

      public ReportController(
         IReportService reportService,
         ISlugService slugService,
         CombinedLogger<ReportController> logger
      ) {
         _reportService = reportService;
         _slugService = slugService;
         _logger = logger;
      }

      [HttpGet]
      public async Task<ActionResult> Index(string contentItemId, bool log = false) {

         var report = await _reportService.Validate(new TransformalizeRequest(contentItemId));

         if (report.Fails()) {
            return report.ActionResult;
         }

         await _reportService.RunAsync(report.Process, null);
         if (report.Process.Status != 200) {
            return View("Log", new LogViewModel(_logger.Log, report.Process, report.ContentItem));
         }

         return log ?
            View("Log", new LogViewModel(_logger.Log, report.Process, report.ContentItem)) : 
            View(new ReportViewModel(report.Process, report.ContentItem, HttpContext.Request.Query, contentItemId) { 
               BreadCrumbs = report.BreadCrumbs,
               Editable = report.Editable
            });

      }

      [HttpGet]
      public async Task<ActionResult> Log(string contentItemId) {
         return await Index(contentItemId, log: true);
      }

      [HttpGet]
      public async Task<ActionResult> Run(string contentItemId, string format = "json") {

         var request = new TransformalizeRequest(contentItemId) { Format = format };
         var report = await _reportService.Validate(request);

         if (report.Fails()) {
            return report.ActionResult;
         }

         await _reportService.RunAsync(report.Process, null);

         report.Process.Connections.Clear();

         return new ContentResult { 
            Content = report.Process.Serialize(), 
            ContentType = request.ContentType 
         };
      }

      [HttpGet]
      public async Task<ActionResult> StreamJson(string contentItemId) {

         var request = new TransformalizeRequest(contentItemId) { Mode = "stream" };
         var stream = await _reportService.Validate(request).ConfigureAwait(false);

         if (stream.Fails()) {
            return stream.ActionResult;
         }

         var o = stream.Process.GetOutputConnection();
         o.Stream = true;
         o.Provider = "json";
         o.File = _slugService.Slugify(stream.ContentItem.As<TitlePart>().Title) + ".json";

         o.Synchronous = true;
         var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();
         if (syncIOFeature != null) {
            syncIOFeature.AllowSynchronousIO = true;
         }

         Response.ContentType = "application/json";
         Response.Headers["content-disposition"] = "attachment; filename=" + o.File;

         StreamWriter sw;

         //await using ((sw = new StreamWriter(Response.Body)).ConfigureAwait(false)) {
         //   await _reportService.RunAsync(stream.Process, sw).ConfigureAwait(false);
         //}

         using (sw = new StreamWriter(Response.Body)) {
            _reportService.Run(stream.Process, sw);
         }

         return new EmptyResult();

      }

      [HttpGet]
      public async Task<ActionResult> StreamGeoJson(string contentItemId) {

         var request = new TransformalizeRequest(contentItemId) { Mode = "stream" };
         var stream = await _reportService.Validate(request).ConfigureAwait(false);

         if (stream.Fails()) {
            return stream.ActionResult;
         }

         var o = stream.Process.GetOutputConnection();
         o.Stream = true;
         o.Provider = "geojson";
         o.File = _slugService.Slugify(stream.ContentItem.As<TitlePart>().Title) + ".geo.json";

         // todo: these will have to be put in report part
         var suppress = new HashSet<string>() { stream.Part.BulkActionValueField.Text, stream.Part.MapColorField.Text, stream.Part.MapDescriptionField.Text };
         var coordinates = new HashSet<string>() { stream.Part.MapLatitudeField.Text, stream.Part.MapLongitudeField.Text };

         foreach (var entity in stream.Process.Entities) {
            foreach (var field in entity.GetAllFields()) {
               if (suppress.Contains(field.Alias)) {
                  field.Output = false;
                  field.Property = false;
                  field.Alias += "Suppressed";
               } else if (coordinates.Contains(field.Alias)) {
                  field.Property = field.Export == "true";
               } else {
                  field.Property = field.Property || field.Output && field.Export == "defer" || field.Export == "true";
               }
            }
         }

         o.Synchronous = true;
         var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();
         if (syncIOFeature != null) {
            syncIOFeature.AllowSynchronousIO = true;
         }

         Response.ContentType = "application/vnd.geo+json";
         Response.Headers["content-disposition"] = "attachment; filename=" + o.File;

         StreamWriter sw;
         
         //await using ((sw = new StreamWriter(Response.Body)).ConfigureAwait(false)) {
         //   await _reportService.RunAsync(stream.Process, sw).ConfigureAwait(false);
         //}

         using (sw = new StreamWriter(Response.Body)) {
            _reportService.Run(stream.Process, sw);
         }

         return new EmptyResult();

      }

      [HttpGet]
      public async Task<ActionResult> StreamCsv(string contentItemId) {

         var request = new TransformalizeRequest(contentItemId) { Mode = "stream" };
         var stream = await _reportService.Validate(request).ConfigureAwait(false);

         if (stream.Fails()) {
            return stream.ActionResult;
         }

         var o = stream.Process.GetOutputConnection();
         o.Stream = true;
         o.Provider = "file";
         o.Delimiter = ",";
         o.TextQualifier = "\"";
         o.File = _slugService.Slugify(stream.ContentItem.As<TitlePart>().Title) + ".csv";

         o.Synchronous = true;
         var syncIOFeature = HttpContext.Features.Get<IHttpBodyControlFeature>();
         if (syncIOFeature != null) {
            syncIOFeature.AllowSynchronousIO = true;
         }

         Response.ContentType = "application/csv";
         Response.Headers.Add("content-disposition", "attachment; filename=" + o.File);

         StreamWriter sw;
         //await using ((sw = new StreamWriter(Response.Body)).ConfigureAwait(false)) {
         //   await _reportService.RunAsync(stream.Process, sw).ConfigureAwait(false);
         //}

         using (sw = new StreamWriter(Response.Body)) {
            _reportService.Run(stream.Process, sw);
         }

         return new EmptyResult();

      }

   }
}

src/OrchardCore.Transformalize/Controllers/SchemaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TransformalizeModule.Models;
using TransformalizeModule.Services;
using TransformalizeModule.Services.Contracts;
using TransformalizeModule.ViewModels;

namespace TransformalizeModule.Controllers {

   [Authorize]
   public class SchemaController : Controller {

      private readonly ISchemaService _schemaService;
      private readonly CombinedLogger<TaskController> _logger;

      public SchemaController(
         ISchemaService taskService,
         CombinedLogger<TaskController> logger
      ) {
         _schemaService = taskService;
         _logger = logger;
      }

      public async Task<ActionResult> Index(string contentItemId, string format = "xml") {

         var request = new TransformalizeRequest(contentItemId) { Format = format };
         var task = await _schemaService.Validate(request);

         if (task.Fails()) {
            return task.ActionResult;
         }

         var process = await _schemaService.GetSchemaAsync(task.Process);

         if (format == null) {
            return View("Log", new LogViewModel(_logger.Log, process, task.ContentItem));
         } else {
            task.Process.Log.AddRange(_logger.Log);
            task.Process.Connections.Clear();
            return new ContentResult() { Content = process.Serialize(), ContentType = request.ContentType };
         }
      }

   }
}

src/OrchardCore.Transformalize/Controllers/TaskController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TransformalizeModule.Models;
using TransformalizeModule.Services;
using TransformalizeModule.Services.Contracts;
using TransformalizeModule.ViewModels;

namespace TransformalizeModule.Controllers {

   [Authorize]
   public class TaskController : Controller {

      private readonly ITaskService _taskService;
      private readonly CombinedLogger<TaskController> _logger;
      private readonly IFormService _formService;

      public TaskController(
         ITaskService taskService,
         IFormService formService,
         CombinedLogger<TaskController> logger
      ) {
         _taskService = taskService;
         _logger = logger;
         _formService = formService;
      }

      public async Task<ActionResult> Run(string contentItemId, string format = null) {

         var request = new TransformalizeRequest(contentItemId) { 
            Format = format, 
            InternalParameters = Common.GetFileParameters(Request)
         };
         var task = await _taskService.Validate(request);

         if (task.Fails()) {
            return task.ActionResult;
         }

         await _taskService.RunAsync(task.Process);

         if (format == null) {
            return View("Log", new LogViewModel(_logger.Log, task.Process, task.ContentItem));
         } else {
            task.Process.Log.AddRange(_logger.Log);
            task.Process.Connections.Clear();
            return new ContentResult() { Content = task.Process.Serialize(), ContentType = request.ContentType };
         }
      }

      public async Task<ActionResult> Form(string contentItemId) {

         var bulkAction = await _formService.ValidateParameters(new TransformalizeRequest(contentItemId));

         if (bulkAction.Fails()) {
            return bulkAction.ActionResult;
         }

         return View("Form", bulkAction.Process);
      }

      public async Task<ActionResult> Review(string contentItemId) {

         var task = await _formService.ValidateParameters(new TransformalizeRequest(contentItemId));

         if (task.Fails()) {
            return task.ActionResult;
         }

         return View(task);
      }

   }
}

src/OrchardCore.Transformalize/Views/NavigationItemText-tfl.Id.cshtml
<span class="icon"><i class="fa fa-subway" aria-hidden="true"></i></span><span class="title">@T["Transformalize"]</span>

src/OrchardCore.Transformalize/Views/TextField-TransformalizeArrangement.Edit.cshtml
@model OrchardCore.ContentFields.ViewModels.EditTextFieldViewModel
@using OrchardCore.ContentFields.Settings
@using OrchardCore.ContentLocalization;
@using OrchardCore.ContentManagement.Metadata.Models
@using OrchardCore.Localization

@{
   var settings = Model.PartFieldDefinition.GetSettings<TextFieldSettings>();
   var culture = await Orchard.GetContentCultureAsync(Model.Field.ContentItem);
}

<div class="form-group">
   <label asp-for="Text" class="form-label">@Model.PartFieldDefinition.DisplayName()</label>
   <textarea asp-for="Text" rows="5" class="form-control content-preview-text" dir="@culture.GetLanguageDirection()"></textarea>
   <div class="hint" style="font-size: smaller;">
      @if (!string.IsNullOrWhiteSpace(settings.Hint)) {
         @settings.Hint<br/>
      }
      <strong>F11</strong>: <span>Full Screen</span>,
      <strong>Esc</strong>: <span>Exit Full Screen</span>,
      <strong>Ctrl-S</strong>: <span>Save</span>,
      <strong>Ctrl-Space</strong>: <span>Auto Complete</span>,
      <strong>Ctrl-F</strong>: <span>Find</span>,
      <strong>Ctrl-G</strong>: <span>Find next</span>,
      <strong>Shift-Ctrl-G</strong>: <span>Find previous</span>,
      <strong>Shift-Ctrl-F</strong>: <span>Replace</span>,
      <strong>Shift-Ctrl-R</strong>: <span>Replace all</span>.
   </div>
</div>

@Html.Partial("CodeMirror", new CodeMirrorViewModel(Html.IdFor(m => m.Text), .5))

src/OrchardCore.Transformalize/Views/TextField-TransformalizeArrangement.Option.cshtml
@{
    string currentEditor = Model.Editor;
}
<option value="TransformalizeArrangement" selected="@(currentEditor == "TransformalizeArrangement")">@T["Transformalize Arrangement"]</option>

src/OrchardCore.Transformalize/Views/TransformalizeFilePart.Edit.cshtml
@model EditTransformalizeFilePartViewModel
@using TransformalizeModule.ViewModels
@using TransformalizeModule

@{
   var Area = Common.ModuleName;
   var ContentItemId = Model.TransformalizeFilePart.ContentItem.ContentItemId;
   var viewLink = Url.Action("Index", "File", new { Area, ContentItemId });
}

<fieldset>
   <div class="btn-group float-right" role="group">
      <a title="view this file"
         role="button"
         class="btn btn-success btn-sm"
         href="@viewLink">
         <span class="fas fa-eye"></span>
      </a>
   </div>
</fieldset>

src/OrchardCore.Transformalize/Views/TransformalizeFormPart.Edit.cshtml
@model EditTransformalizeFormPartViewModel
@using TransformalizeModule.ViewModels
@using TransformalizeModule

@{
   var Area = Common.ModuleName;
   var ContentItemId = Model.TransformalizeFormPart.ContentItem.ContentItemId;
   var xmlLink = Url.Action("Run", "Form", new { Format = "xml", Area, ContentItemId });
   var jsonLink = Url.Action("Run", "Form", new { Format = "json", Area, ContentItemId });
   var viewLink = Url.Action("Index", "Form", new { Area, ContentItemId });
}

<fieldset>
   <div class="btn-group float-right" role="group">
      <a title="view this task"
         role="button"
         class="btn btn-success btn-sm"
         href="@viewLink">
         <span class="fas fa-eye"></span>
      </a>
      <a title="run this report as xml"
         href="@xmlLink"
         class="btn btn-primary btn-sm"
         role="button">
         <span class="fas fa-code"></span>
      </a>
      <a title="run this report as json"
         role="button"
         class="btn btn-secondary btn-sm"
         href="@jsonLink">
         <span class="fas fa-exchange-alt"></span>
      </a>
   </div>
</fieldset>

@if (Model.CreateCommand != string.Empty) {
   <fieldset>

      <table class="table table-sm">
         <thead>
            <tr>
               <th scope="col">Type</th>
               <th scope="col">Command</th>
            </tr>
         </thead>
         <tbody>
            <tr>
               <td>Create</td>
               <td><code>@Model.CreateCommand</code></td>
            </tr>
            <tr>
               <td>Insert</td>
               <td><code>@Model.InsertCommand</code></td>
            </tr>
            <tr>
               <td>Update</td>
               <td><code>@Model.UpdateCommand</code></td>
            </tr>
            <tr>
               <td>Select</td>
               <td><code>@Model.SelectCommand</code></td>
            </tr>
         </tbody>
      </table>

   </fieldset>
}

src/OrchardCore.Transformalize/Views/TransformalizeReportPart.Edit.cshtml
@model EditTransformalizeReportPartViewModel
@using TransformalizeModule.ViewModels;
@using TransformalizeModule 

@{
   var Area = Common.ModuleName;
   var ContentItemId = Model.TransformalizeReportPart.ContentItem.ContentItemId;
   var viewLink = Url.Action("Index", "Report", new { Area , ContentItemId });
   var xmlLink = Url.Action("Run", "Report", new { Format = "xml", Area, ContentItemId });
   var jsonLink = Url.Action("Run", "Report", new { Format = "json", Area, ContentItemId });
   var logLink = Url.Action("Log", "Report", new { Format = "json", Area, ContentItemId });
   var schemaLink = Url.Action("Index", "Schema", new { Format = "xml", Area, ContentItemId });
}

<fieldset>
   <div class="btn-group float-right" role="group">
      <a href="@viewLink" class="btn btn-success btn-sm" role="button" title="view this report">
         <span class="fas fa-eye"></span>
      </a>
      <a href="@xmlLink" class="btn btn-primary btn-sm" role="button" title="run this report as xml">
         <span class="fas fa-code"></span>
      </a>
      <a title="run this report as json" role="button" class="btn btn-secondary btn-sm" href="@jsonLink">
         <span class="fas fa-exchange-alt"></span>
      </a> 
      <a title="view this report's log" role="button" class="btn btn-warning btn-sm" href="@logLink">
         <span class="fas fa-clipboard-list"></span>
      </a>
      <a title="query schema for the entity in this report" role="button" class="btn btn-info btn-sm" href="@schemaLink">
         <span class="fas fa-search-plus"></span>
      </a>
   </div>
</fieldset>

src/OrchardCore.Transformalize/Views/TransformalizeSettings.Edit.cshtml
@model TransformalizeModule.ViewModels.TransformalizeSettingsViewModel
@using TransformalizeModule 

   <ul class="nav nav-tabs">
      <li class="nav-item pr-md-2">
         <a class="nav-link active" id="main-tab" data-bs-toggle="tab" href="#main" role="tab" aria-controls="main" aria-selected="true">@T["Main"]</a>
      </li>
      <li class="nav-item pr-md-2">
         <a class="nav-link" id="bulk-tab" data-bs-toggle="tab" href="#bulk" role="tab" aria-controls="bulk">@T["Bulk Actions"]</a>
      </li>
      <li class="nav-item">
         <a class="nav-link" id="keys-tab" data-bs-toggle="tab" href="#keys" role="tab" aria-controls="keys">@T["Keys"]</a>
      </li>
   </ul>

<div class="tab-content" id="tabs">

   <div class="tab-pane fade show active" id="main" role="tabpanel" aria-labelledby="main-tab">

      <div class="form-group">
         <label asp-for="CommonArrangement" class="form-label">@T["Common Arrangement"]</label>
         <textarea asp-for="CommonArrangement" rows="5" class="form-control content-preview-text"></textarea>
         <div class="hint" style="font-size: smaller;">
            <strong>F11</strong>: <span>Full Screen</span>,
            <strong>Esc</strong>: <span>Exit Full Screen</span>,
            <strong>Ctrl-S</strong>: <span>Save</span>,
            <strong>Ctrl-Space</strong>: <span>Auto Complete</span>,
            <strong>Ctrl-F</strong>: <span>Find</span>,
            <strong>Ctrl-G</strong>: <span>Find next</span>,
            <strong>Shift-Ctrl-G</strong>: <span>Find previous</span>,
            <strong>Shift-Ctrl-F</strong>: <span>Replace</span>,
            <strong>Shift-Ctrl-R</strong>: <span>Replace all</span>.
         </div>
         <span class="hint">@T["This arrangement stores common items (i.e. connections) that may be referenced by name in other arrangements."]</span>
      </div>

      @Html.Partial("CodeMirror", new CodeMirrorViewModel(Html.IdFor(m => m.CommonArrangement), .5))

      <div class="form-group">
         <label asp-for="DefaultPageSizes" class="form-label">@T["Default Page Sizes"]</label>
         <input asp-for="DefaultPageSizes" class="form-control" />
         <span class="hint">@T["A comma delimited list of page sizes (integers).  These are used for all reports that do not set a page sizes."]</span>
      </div>

      <div class="form-group">
         <label asp-for="DefaultPageSizesExtended" class="form-label">@T["Default Page Sizes Extended"]</label>
         <input asp-for="DefaultPageSizesExtended" class="form-control" />
         <span class="hint">@T["A comma delimited list of extended page sizes (integers).  These are used for all calendars and/or maps that do not set page sizes."]</span>
      </div>

   </div>

   <div class="tab-pane fade" id="bulk" role="tabpanel" aria-labelledby="bulk-tab">

      <div class="form-group">
         <label asp-for="BulkActionCreateTask" class="form-label">@T["Create Task"]</label>
         <input asp-for="BulkActionCreateTask" class="form-control" />
         <span class="hint">@T[Common.BulkActionCreateTaskHint]</span>
      </div>

      <div class="form-group">
         <label asp-for="BulkActionWriteTask" class="form-label">@T["Write Task"]</label>
         <input asp-for="BulkActionWriteTask" class="form-control" />
         <span class="hint">@T[Common.BulkActionWriteTaskHint]</span>
      </div>

      <div class="form-group">
         <label asp-for="BulkActionSummaryTask" class="form-label">@T["Summary Task"]</label>
         <input asp-for="BulkActionSummaryTask" class="form-control" />
         <span class="hint">@T[Common.BulkActionSummaryTaskHint]</span>
      </div>

      <div class="form-group">
         <label asp-for="BulkActionRunTask" class="form-label">@T["Run Task"]</label>
         <input asp-for="BulkActionRunTask" class="form-control" />
         <span class="hint">@T[Common.BulkActionRunTaskHint]</span>
      </div>

      <div class="form-group">
         <label asp-for="BulkActionSuccessTask" class="form-label">@T["Success Task"]</label>
         <input asp-for="BulkActionSuccessTask" class="form-control" />
         <span class="hint">@T[Common.BulkActionSuccessTaskHint]</span>
      </div>

      <div class="form-group">
         <label asp-for="BulkActionFailTask" class="form-label">@T["Fail Task"]</label>
         <input asp-for="BulkActionFailTask" class="form-control" />
         <span class="hint">@T[Common.BulkActionFailTaskHint]</span>
      </div>

   </div>

   <div class="tab-pane fade" id="keys" role="tabpanel" aria-labelledby="keys-tab">

      <div class="form-group">
         <label asp-for="MapBoxToken" class="form-label">@T["MapBox Token"]</label>
         <input asp-for="MapBoxToken" class="form-control" />
         <span class="hint">@T["Get a token at "] <a href="https://www.mapbox.com" target="_blank">https://www.mapbox.com</a>.</span>
      </div>

      <div class="form-group">
         <label asp-for="GoogleApiKey" class="form-label">@T["Google API Key"]</label>
         <input asp-for="GoogleApiKey" class="form-control" />
         <span class="hint">@T["Get a key at "] <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" target="_blank">GCP</a>.  Grant access to Places API and Maps JavaScript API.
   </div>

</div>

src/OrchardCore.Transformalize/Views/TransformalizeTaskPart.Edit.cshtml
@model EditTransformalizeTaskPartViewModel
@using TransformalizeModule.ViewModels
@using TransformalizeModule

@{
   var Area = Common.ModuleName;
   var ContentItemId = Model.TransformalizeTaskPart.ContentItem.ContentItemId;
   var viewLink = Url.Action("Review", "Task", new { Area, ContentItemId });
   var runLink = Url.Action("Run", "Task", new { Area, ContentItemId });
   var xmlLink = Url.Action("Run", "Task", new { Format = "xml", Area, ContentItemId });
   var jsonLink = Url.Action("Run", "Task", new { Format = "json", Area, ContentItemId });
   var schemaLink = Url.Action("Index", "Schema", new { Format = "xml", Area, ContentItemId });
}

<fieldset>
   <div class="btn-group float-right" role="group">
      <a title="view this task"
         role="button"
         class="btn btn-success btn-sm"
         href="@viewLink">
         <span class="fas fa-eye"></span>
      </a>
      <a title="run this task"
         role="button"
         class="btn btn-warning btn-sm"
         href="@runLink">
         <span class="fas fa-play"></span>
      </a>
      <a title="run this task as xml"
         role="button"
         class="btn btn-primary btn-sm"
         href="@xmlLink">
         <span class="fas fa-code"></span>
      </a>
      <a title="run this task as json"
         role="button"
         class="btn btn-secondary btn-sm"
         href="@jsonLink">
         <span class="fas fa-exchange-alt"></span>
      </a>
      <a title="query schema for the entities in this task"
         role="button"
         class="btn btn-info btn-sm"
         href="@schemaLink">
         <span class="fas fa-search-plus"></span>
      </a>
   </div>
</fieldset>